apiVersion: v1
kind: Service
metadata:
  name: service-hello-world
  labels: 
    app: hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: hello-world

